#132. Added breadcrumbs.
ozin7/commerce_draft pull request #136
Opened 2023-03-20 17:38 UTC by serhii-morozov

commerce_draft-132: Added breadcrumbs - easy_breadcrumbs module. Added product categories to breadcrumbs.

2023-03-21 16:33 UTC, Macsym2018 commented on config/default/block.block.breadcrumbs.yml
> +region: header
It is better to display breadcrumbs in the breadcrumbs region.
And maybe change visibility only for Commerce Product.

2023-03-21 16:39 UTC, Macsym2018 requested changes
It is better to display breadcrumbs in the breadcrumbs region.
Maybe you need to make the block visible only for the productpage.

2023-03-27 08:55 UTC, Macsym2018 commented
> 
@serhii-morozov 
There is the "Breadcrumb" region in Block Layout by default.

2023-04-19 07:43 UTC, ozin7 requested changes

2023-04-19 07:43 UTC, ozin7 commented on docroot/modules/custom/draft_wishlist/draft_wishlist.info.yml
You remove this module but this module is not disabled in core.extention.
If you want to remove module you have to disable it first, then deploy this to prod and then with next deploy you can remove the module code

2024-04-18 06:52 UTC, closed without merging